- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./dockerfile/Dockerfile
      buildContext: .
      tag: example-jumpbox:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./jump.yaml
