---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jumpbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jumpbox
      version: v1
  template:
    metadata:
      labels:
        app: jumpbox
        version: v1
    spec:
      containers:
      - image: jkritzen/jumphost
        imagePullPolicy: Always
        name: jumpbox
        ports:
        - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: my-jump
spec:
  clusterIP: 
  externalTrafficPolicy: Cluster
  ports:
  - name: tcp-ssh
    nodePort:
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: jumpbox
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jump-allow-external-egress-ssh
spec:
  podSelector:
    matchLabels:
      app: jumpbox
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 10.30.1.0/24
    - ipBlock:
        cidr: 10.30.10.0/24
    ports:
    - protocol: TCP
      port: 22
  - to:
    - namespaceSelector: {}
