---
apiVersion: apps/v1
kind: Deployment
metadata:
name: myjump
namespace: jumptest
replicas: 1
revisionHistoryLimit: 10
strategy:
rollingUpdate:
maxSurge: 1
maxUnavailable: 0
type: RollingUpdate
spec:
containers:
- env:
- name: admin_pubkey
value: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0j9UAe85Gs5Qq0lepbxKDCFZKBuhS3TPa/ycQ27UcbC8iRl5kGXh/cU7e17eeu2qoLdcC5InMD2hodmopV92G6vwjGSoq596khgarHsKV+8sna/2XVW+EFkTSHs648iuUozlaCZQUh9ghfGsExxsqp+ZPW71gt9eqBRD/KwDyJv/g4UISDQEgwY7QGOiDF7SIcPlhYWrUST+55d/GLClTWXnmt43bWAPJuRDWq//z97O/gRAeRGsV034NuMwNzw2LcIIws12VYEsLT3Q3jqWcP8lfHHlmud9MdXb6jZjxRUmO8CW23vVndQxj5riLa5nBPCUKjNYCTYJiXXxZtW/5
jkritzen
- name: admin_user
value: jkritzen
image: jkritzen/jumpservice
imagePullPolicy: Always
livenessProbe:
failureThreshold: 3
initialDelaySeconds: 10
periodSeconds: 2
successThreshold: 1
tcpSocket:
port: 22
timeoutSeconds: 2
name: myjump
ports:
- containerPort: 22
name: sshd
protocol: TCP
readinessProbe:
failureThreshold: 3
initialDelaySeconds: 10
periodSeconds: 2
successThreshold: 2
tcpSocket:
port: 22
timeoutSeconds: 2
resources: {}
securityContext:
allowPrivilegeEscalation: true
privileged: false
readOnlyRootFilesystem: false
runAsNonRoot: false
stdin: true
terminationMessagePath: /dev/termination-log
terminationMessagePolicy: File
tty: true
volumeMounts:
- mountPath: /etc/ssh/keys
name: jumpkeys
dnsPolicy: ClusterFirst
imagePullSecrets:
- name: mygithub
restartPolicy: Always
schedulerName: default-scheduler
securityContext: {}
terminationGracePeriodSeconds: 30
volumes:
- name: jumpkeys
secret:
defaultMode: 384
items:
- key: ssh_host_rsa_key
path: ssh_host_rsa_key
- key: ssh_host_rsa_key.pub
path: ssh_host_rsa_key.pub
optional: false
secretName: jumphostkeys
---
apiVersion: v1
kind: Service
metadata:
name: myjump-nodeport
namespace: jumptest
controller: true
kind: deployment
name: myjump
spec:
externalTrafficPolicy: Cluster
ports:
- name: sshd
nodePort: 30022
port: 22
protocol: TCP
targetPort: 22
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jump-allow-external-egress-ssh
spec:
  podSelector:
    matchLabels:
      app: jumpbox
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 10.30.1.0/24
    - ipBlock:
        cidr: 10.30.10.0/24
    ports:
    - protocol: TCP
      port: 22
  - to:
    - namespaceSelector: {}
